name: Node.js CI

on:
  push:
    branches: [ "k3s-local" ]


jobs:
  build:

    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v4
    - name: setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - name: Find package.json
      run: |
       find . -name "package.json"
       find . -name "package-lock.json"

    - name: install dependences
      working-directory: client
      run: npm ci

    - name: run tast
      working-directory: client
      run: npm test
